jobs:
- job: Strategy_build
  steps:

  - template: build/build-dotnet.yml@templates
    parameters:
      sourceCodeDirectory: 'Behavioral/Strategy/source'
      testsCodeDirectory: 'Behavioral/Strategy/tests'
      dotnetCoreVersion: '8.0.x'
      artifactName: 'ConsolePackage'
      buildConfiguration: 'Release'