jobs:
- job: Adapter_build
  steps:

  - template: build/build-dotnet.yml@templates
    parameters:
      sourceCodeDirectory: 'Structural/Adapter/source'
      testsCodeDirectory: 'Structural/Adapter/tests'
      dotnetCoreVersion: '8.0.x'
      artifactName: 'ConsolePackage'
      buildConfiguration: 'Release'