jobs:
- job: factory_build
  steps:

  - template: build/build-dotnet.yml@templates
    parameters:
      sourceCodeDirectory: 'Creational\Factory\source\'
      dotnetCoreVersion: '8.0.x'
      artifactName: 'functionPackage'
      buildConfiguration: 'Release'
      nodejsVersion: '15.x'
      hasSqlFiles: false