resources:
  repositories:
  - repository: xulongjunGitHubRepo    # Name used to refer to this repository
    type: github
    name: xulongjun/pipeline-templates  # Repository name in the format UserName/RepoName
    ref: refs/heads/main  

trigger:
  - none
      
stages:
- stage: Build
  pool: "DTC-ATHFR-POOL-STG"
  jobs:
  - template: build.yml
    parameters:
      localpath: ${{variables['System.DefaultWorkingDirectory']}}/pipeline/