jobs:
- job: Composite_build
  steps:

  - template: build/build-dotnet.yml@templates
    parameters:
      sourceCodeDirectory: 'Structural/Composite/source'
      testsCodeDirectory: 'Structural/Composite/tests'
      dotnetCoreVersion: '8.0.x'
      artifactName: 'ConsolePackage'
      buildConfiguration: 'Release'