jobs:
- job: XXXXX_build
  steps:

  - template: build/build-dotnet.yml@templates
    parameters:
      sourceCodeDirectory: 'Creational/XXXXX/source'
      testsCodeDirectory: 'Creational/XXXXX/tests'
      dotnetCoreVersion: '8.0.x'
      artifactName: 'ConsolePackage'
      buildConfiguration: 'Release'