jobs:
- job: Bridge_build
  steps:

  - template: build/build-dotnet.yml@templates
    parameters:
      sourceCodeDirectory: 'Structural/Bridge/source'
      testsCodeDirectory: 'Structural/Bridge/tests'
      dotnetCoreVersion: '8.0.x'
      artifactName: 'ConsolePackage'
      buildConfiguration: 'Release'